# Site settings
title: Duimon-Mega-Bezel-Graphics
email: ""
description: "Duimon-Mega-Bezel-Graphics"
url: ""
baseurl: "/Gallery-Guides"
github_username:  "Duimon"
deviantart_username: "dhuseby"
youtube_username: "UCKlEnrgZRGEhQU3qs_jEoaA"
discus_shortname: ""
share: true

# Owner/author information
owner:
  name:   Duimon
  avatar: avatar.png
  favicon: favicon.ico
  info: Duimon-Mega-Bezel-Graphics

# Settings for comments helper
# Set 'provider' to the comment provider you want to use. (i.e.  Disqus, Intense Debate, livefyre, or Facebook Comments)
# Set 'provider' to false to turn commenting off globally.
#Set 'provider: false' to disable comments globally.
# Disable comments for individual pages/posts by specifying 'comments: false' in the page/post YAML Front Matter.
#
comments :
  provider : disqus
  disqus :
    short_name : ""

# Internal nav
nav:
  - GALLERY: "/Gallery-Guides/gallery/"  
  - GUIDES: "/Gallery-Guides/guides/"
  - ABOUT: "/Gallery-Guides/about/"

# All translation keys
translations:
 # 404.html
  permalink: "/404.html"

# Server
destination:      	 ./_site
port:             	 4000


# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
paginate_path: "/guides/page:num/"
permalink: "/guides/:title/"
categories_path: "/guides/category/"
tags_path: "/guides/tag/"
gems: 
 - jekyll-paginate
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# SiteMap
sitemap:
    file: "/sitemap.xml"
    exclude:
        - "/atom.xml"
        - "/feed.xml"
        - "/feed/index.xml"
    include_posts:
        - "/writing/"
    change_frequency_name: "change_frequency"
    priority_name: "priority"
